global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8000']
        labels:
          service: 'api-gateway'

  - job_name: 'product-service'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['product-service:3000']
        labels:
          service: 'product-service'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093